client.findAll = SELECT * FROM ais_wedding_agency.client ORDER BY lastname, name, middle_name
client.findById = SELECT * FROM ais_wedding_agency.client WHERE id = ?
client.save = INSERT INTO ais_wedding_agency.client(phone_number, email, name, lastname, middle_name,gender, date_of_registration, place_of_birth, series, number, issued_by, when_issued, registration_adress) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
client.delete = DELETE FROM ais_wedding_agency.client WHERE id = ?
client.update =UPDATE ais_wedding_agency.client SET phone_number = ?, email = ?, name = ?, lastname = ?, middle_name = ?, gender = ?, date_of_registration = ?, place_of_birth = ?, series = ?, number = ?, issued_by = ?, when_issued = ?, registration_adress = ? WHERE id = ?
client.search = SELECT * FROM ais_wedding_agency.client WHERE name ILIKE ? OR lastname ILIKE ? OR middle_name ILIKE ? ORDER BY lastname, name, middle_name
contractor.findById = SELECT * FROM ais_wedding_agency.contractor WHERE id = ?
contractor.findAll = SELECT * FROM ais_wedding_agency.contractor
contractor.save = INSERT INTO ais_wedding_agency.contractor(phone_number, email, name, lastname) VALUES(?,?,?,?)
contractor.delete = DELETE FROM ais_wedding_agency.contractor WHERE id = ?
contractor.update = UPDATE ais_wedding_agency.contractor SET phone_number = ?, email = ?, name = ?, lastname = ? WHERE id = ?
contractor.search = SELECT * FROM ais_wedding_agency.contractor WHERE phone_number ILIKE ? OR name ILIKE ? OR lastname ILIKE ?
contractorService.findById = SELECT * FROM ais_wedding_agency.contractor_service WHERE id = ?
contractorService.findAll = SELECT * FROM ais_wedding_agency.contractor_service
contractorService.save = INSERT INTO ais_wedding_agency.contractor_service(contractor_id, service, price, prepayment) VALUES(?,?,?,?)
contractorService.delete = DELETE FROM ais_wedding_agency.contractor_service WHERE id = ?
contractorService.update = UPDATE ais_wedding_agency.contractor_service SET contractor_id = ?, service = ?, price = ?, prepayment = ? WHERE id = ?
contractorService.search = SELECT * FROM ais_wedding_agency.service_search(?,?,?,?)
contractorService.findByContractorId = SELECT * FROM ais_wedding_agency.contractor_service WHERE contractor_id = ?
contractorService.contrHaveAnyTasks = SELECT * FROM ais_wedding_agency.contrHaveTasksInProject(?,?)
contractorService.serviceExists = SELECT * FROM ais_wedding_agency.service_exists(?,?)
guest.addGuest = INSERT INTO ais_wedding_agency.project_guest(guest_id,project_id) VALUES(?,?)
guest.findById = SELECT * FROM ais_wedding_agency.guest WHERE id = ?
guest.findAll = SELECT * FROM ais_wedding_agency.guest ORDER BY lastname, name, middle_name
guest.save = INSERT INTO ais_wedding_agency.guest(name, lastname, middle_name) VALUES(?,?,?)
guest.delete = DELETE FROM ais_wedding_agency.guest WHERE id = ?
guest.update = UPDATE ais_wedding_agency.guest SET name = ?, lastname = ?, middle_name = ? WHERE id = ?
guest.search = SELECT * FROM ais_wedding_agency.guest WHERE name ILIKE ? OR lastname ILIKE ? OR middle_name ILIKE ?
guest.findByProject = SELECT g.* FROM ais_wedding_agency.guest g JOIN ais_wedding_agency.project_guest pg ON g.id = pg.guest_id WHERE pg.project_id = ?
guest.deleteFromProject = DELETE FROM ais_wedding_agency.project_guest WHERE project_id = ? AND guest_id = ?
guest.isItProjectGuest = SELECT * FROM ais_wedding_agency.is_it_project_guest(?,?)
portfolio.findById = SELECT * FROM ais_wedding_agency.portfolio WHERE id = ?
portfolio.findAll = SELECT * FROM ais_wedding_agency.portfolio
portfolio.save = INSERT INTO ais_wedding_agency.portfolio(description, contractor_id, image_url) VALUES(?,?,?)
portfolio.delete = DELETE FROM ais_wedding_agency.portfolio WHERE id = ?
portfolio.update = UPDATE ais_wedding_agency.portfolio SET description = ?, contractor_id = ?, image_url = ? WHERE id = ?
portfolio.search = SELECT * FROM ais_wedding_agency.portfolio WHERE description ILIKE ? AND contractor_id = ?
portfolio.findByContractor = SELECT * FROM ais_wedding_agency.portfolio WHERE contractor_id = ?
portfolio.portfolioExists = SELECT * FROM ais_wedding_agency.portfolio_exists(?,?)
projectClient.findById = SELECT * FROM ais_wedding_agency.project_client WHERE id = ?
projectClient.findAll = SELECT * FROM ais_wedding_agency.project_client
projectClient.save = INSERT INTO ais_wedding_agency.project_client(project_id, client_id, role) VALUES(?,?,?)
projectClient.delete = DELETE FROM ais_wedding_agency.project_client WHERE id = ?
projectClient.update = UPDATE ais_wedding_agency.project_client SET project_id = ?, client_id = ?, role = ? WHERE id = ?
project.findAll = SELECT * FROM ais_wedding_agency.project
project.findById = SELECT * FROM ais_wedding_agency.project WHERE id = ?
project.save = INSERT INTO ais_wedding_agency.project(wedding_date, status, wishes_for_wedding) VALUES(?,?,?)
project.delete = DELETE FROM ais_wedding_agency.project WHERE id = ?
project.update = UPDATE ais_wedding_agency.project SET wedding_date = ?, status = ?, wishes_for_wedding = ? WHERE id = ?
project.searchByDate = SELECT * FROM ais_wedding_agency.project WHERE wedding_date = ?
project.addSpouses = INSERT INTO ais_wedding_agency.project_client(project_id,client_id,role) VALUES(?,?,?)
project.relatedProjects = SELECT p.* FROM ais_wedding_agency.project p INNER JOIN ais_wedding_agency.project_client pc ON p.id = pc.project_id WHERE pc.client_id = ?
project.addContractorToProject = INSERT INTO ais_wedding_agency.used_contractor(project_id,contractor_id) VALUES(?,?)
project.findContractorsByProject = SELECT c.* FROM ais_wedding_agency.contractor c INNER JOIN ais_wedding_agency.used_contractor uc ON c.id = uc.contractor_id WHERE uc.project_id = ?
project.findClientsByProject = SELECT pc.id as pc_id, pc.role, c.id as client_id, c.name, c.lastname, c.middle_name FROM ais_wedding_agency.project_client pc INNER JOIN ais_wedding_agency.client c ON pc.client_id = c.id WHERE pc.project_id = ?
report.findById = SELECT * FROM ais_wedding_agency.report WHERE id = ?
report.findAll = SELECT * FROM ais_wedding_agency.report
report.save = INSERT INTO ais_wedding_agency.report(project_id, total_budget, completed_tasks_count, amount_of_guests) VALUES(?,?,?,?)
report.delete = DELETE FROM ais_wedding_agency.report WHERE id = ?
report.update = UPDATE ais_wedding_agency.report SET total_budget = ?, completed_tasks_count = ?, amount_of_guests = ? WHERE project_id = ?
report.search = SELECT * FROM ais_wedding_agency.report WHERE project_id = ?
report.reportStats = SELECT * FROM ais_wedding_agency.get_report_stats(?)
task.findById = SELECT * FROM ais_wedding_agency.task WHERE id = ?
task.findAll = SELECT * FROM ais_wedding_agency.task
task.save = INSERT INTO ais_wedding_agency.task(contractor_service_id, price, status, deadline, priority, project_id) VALUES(?,?,?,?,?,?)
task.delete = DELETE FROM ais_wedding_agency.task WHERE id = ?
task.update = UPDATE ais_wedding_agency.task SET contractor_service_id = ?, price = ?, status = ?, deadline = ?, priority = ?, project_id = ? WHERE id = ?
task.search = SELECT * FROM ais_wedding_agency.task_search(?,?,?)
task.findByProject = SELECT * FROM ais_wedding_agency.task WHERE project_id = ?
usedContractor.findById = SELECT * FROM ais_wedding_agency.used_contractor WHERE id = ?
usedContractor.findAll = SELECT * FROM ais_wedding_agency.used_contractor
usedContractor.save = INSERT INTO ais_wedding_agency.used_contractor(project_id, contractor_id) VALUES(?,?)
usedContractor.delete = DELETE FROM ais_wedding_agency.used_contractor WHERE id = ?
usedContractor.update = UPDATE ais_wedding_agency.used_contractor SET project_id = ?, contractor_id = ? WHERE id = ?
usedContractor.findByProjectAndContractor = SELECT * FROM ais_wedding_agency.used_contractor WHERE project_id = ? AND contractor_id = ?






